### ISSUE TITLE
(Vertex)Generators not correctly initialized in multithreaded mode

### ISSUE THREAD

**Issue by gipert** [gipert/remage#10]
The G4 dynamics of UI command execution in multithreaded mode lead to too-early execution of generator-specific commands, at a stage in which the latter commands have not been defined yet. Need to think about a way to make sure that the generator object is constructed early enough during execution. I've documented the issue in a [post on the G4 user forum](https://geant4-forum.web.cern.ch/t/generator-messenger-commands-in-multi-threaded-mode).

**Comment by ManuelHu** [comment]
The note in https://github.com/Geant4/geant4/blob/99d10a46dc78367c58913995519648b8b2610d56/source/event/include/G4GeneralParticleSourceMessenger.hh#L221-L240 is right. Initializing the `RMGMasterGenerator` in `BuildForMaster` makes the MT mode work. PR will follow.
